# Generated by Django 5.1.4 on 2025-11-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='api.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
