# Generated by Django 5.1.4 on 2025-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_language_alter_book_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="languages",
        ),
        migrations.AddField(
            model_name="book",
            name="languages",
            field=models.ManyToManyField(to="api.language"),
        ),
    ]
