# Generated by Django 5.1.4 on 2025-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_book_languages_book_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="name",
            field=models.CharField(default="Placeholder", max_length=255, unique=True),
        ),
    ]
