# Generated by Django 5.1.4 on 2025-11-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_book_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="name",
        ),
    ]
