# Generated by Django 5.1.4 on 2025-12-19 12:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_book_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                (
                    "profileImage",
                    models.ImageField(
                        blank=True,
                        default=api.models.getDefaultImage,
                        null=True,
                        upload_to="profiles",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("borrowed_books", models.ManyToManyField(blank=True, to="api.book")),
            ],
        ),
    ]
