# Generated by Django 5.1.4 on 2025-12-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
